name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    uses: LadenzEntrum/ci-templates/.github/workflows/ci.yml@d36a170e52a6ad5ff9775af55906618514667dde
    with:
      runtime: node
